import type { Metadata } from 'next'
import './globals.css'
import { sansFont } from '~/lib/font'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="zh-TW">
      <body className={`${sansFont.variable} font-sans`} >{children}</body>
    </html>
  )
}
