import './globals.css';
import './antd.css';

import type { Metadata } from 'next';

import Header from '~/components/Header';
import { sansFont } from '~/lib/font';

import StyledComponentsRegistry from './AntdRegistry';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh-TW">
      <body className={`${sansFont.variable} font-sans text-config-text`}>
        <StyledComponentsRegistry>
          <Header />
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
